 before_script:
   - docker info
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   
 build_image:
   script:
     - docker build --tag $CI_REGISTRY_IMAGE:latest .

 push_image:
   script:
     - docker push $CI_REGISTRY_IMAGE:latest
