version: "3.7"
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: 'localhost'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://localhost'
          gitlab_rails['gitlab_shell_ssh_port'] = 2222
          gitlab_rails['gitlab_default_projects_features_container_registry'] = true
          registry_external_url 'http://localhost:4567'

        # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
        - '4567:4567'
#       volumes:
#         - './runtime/gitlab/etc/gitlab:/etc/gitlab'
#         - './runtime/var/log/gitlab:/var/log/gitlab'
#         - './runtime/var/opt/gitlab:/var/opt/gitlab'

    gitlab-runner:
      depends_on:
        - gitlab
      network_mode: host
      image: 'gitlab/gitlab-runner:latest'
      restart: always
      hostname: 'localhost'
      volumes: 
        - '$HOME/gitlab-runner-volume/config:/etc/gitlab-runner' 
        - '/var/run/docker.sock:/var/run/docker.sock'
